// Email service for sending audit reports

import nodemailer from 'nodemailer'
import { AuditResult } from '../types.js'
import { GMAIL_USER, GMAIL_APP_PASSWORD, GMAIL_TO } from '../config.js'

// Generate HTML email content
function generateEmailHtml(result: AuditResult): string {
  const passEmoji = '✅'
  const failEmoji = '❌'
  
  const perfStatus = result.summary.performance >= 80 ? passEmoji : failEmoji
  const seoStatus = result.summary.seo >= 90 ? passEmoji : failEmoji

  let pagesHtml = ''
  for (const page of result.pages) {
    const perfColor = (page.performance ?? 0) >= 80 ? '#22c55e' : '#ef4444'
    const seoColor = (page.seo ?? 0) >= 90 ? '#22c55e' : '#ef4444'
    
    pagesHtml += `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${page.path}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center; color: ${perfColor}; font-weight: bold;">${page.performance}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center; color: ${seoColor}; font-weight: bold;">${page.seo}</td>
      </tr>
    `
  }

  let failedHtml = ''
  if (result.failedPages.length > 0) {
    failedHtml = `
      <h3 style="color: #ef4444; margin-top: 24px;">⚠️ Pages Below Threshold (${result.failedPages.length})</h3>
      <ul style="color: #6b7280;">
        ${result.failedPages.map(p => `<li><strong>${p.path}</strong> - Performance: ${p.performance}, SEO: ${p.seo}</li>`).join('')}
      </ul>
    `
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #f9fafb;">
      <div style="background: white; border-radius: 8px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
        <h1 style="color: #111827; margin-bottom: 8px;">🔍 Unlighthouse Audit Report</h1>
        <p style="color: #6b7280; margin-top: 0;">
          <strong>URL:</strong> ${result.url}<br>
          <strong>Time:</strong> ${new Date(result.timestamp).toLocaleString()}
        </p>
        
        <h2 style="color: #374151; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">📊 Summary</h2>
        <div style="display: flex; gap: 24px; margin-bottom: 24px;">
          <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; flex: 1; text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: ${result.summary.performance >= 80 ? '#22c55e' : '#ef4444'};">
              ${result.summary.performance}
            </div>
            <div style="color: #6b7280;">Performance ${perfStatus}</div>
            <div style="font-size: 12px; color: #9ca3af;">Target: ≥80</div>
          </div>
          <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; flex: 1; text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: ${result.summary.seo >= 90 ? '#22c55e' : '#ef4444'};">
              ${result.summary.seo}
            </div>
            <div style="color: #6b7280;">SEO ${seoStatus}</div>
            <div style="font-size: 12px; color: #9ca3af;">Target: ≥90</div>
          </div>
        </div>

        ${failedHtml}

        <h2 style="color: #374151; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin-top: 24px;">📄 All Pages (${result.pages.length})</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #f3f4f6;">
              <th style="padding: 12px 8px; text-align: left; border-bottom: 2px solid #e5e7eb;">Page</th>
              <th style="padding: 12px 8px; text-align: center; border-bottom: 2px solid #e5e7eb;">Performance</th>
              <th style="padding: 12px 8px; text-align: center; border-bottom: 2px solid #e5e7eb;">SEO</th>
            </tr>
          </thead>
          <tbody>
            ${pagesHtml}
          </tbody>
        </table>

        <p style="color: #9ca3af; font-size: 12px; margin-top: 24px; text-align: center;">
          Generated by Audit Server • Powered by Unlighthouse
        </p>
      </div>
    </body>
    </html>
  `
}

// Send email with audit results
export async function sendAuditEmail(result: AuditResult): Promise<boolean> {
  if (!GMAIL_USER || !GMAIL_APP_PASSWORD || !GMAIL_TO) {
    console.error('[Email] Missing Gmail configuration. Set GMAIL_USER, GMAIL_APP_PASSWORD, and GMAIL_TO in .env')
    return false
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: GMAIL_USER,
      pass: GMAIL_APP_PASSWORD
    }
  })

  const perfStatus = result.summary.performance >= 80 ? '✅' : '❌'
  const seoStatus = result.summary.seo >= 90 ? '✅' : '❌'
  const subject = `[Audit] ${result.url} - Performance: ${result.summary.performance} ${perfStatus} | SEO: ${result.summary.seo} ${seoStatus}`

  try {
    await transporter.sendMail({
      from: GMAIL_USER,
      to: GMAIL_TO,
      subject,
      html: generateEmailHtml(result)
    })
    console.log(`[Email] Report sent to ${GMAIL_TO}`)
    return true
  } catch (error) {
    console.error('[Email] Failed to send email:', error)
    return false
  }
}
